language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '6'
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
  # Setup Github Push
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - npm run build
  - npm run deploy
branches:
  except:
    - /^v\d+\.\d+\.\d+$/