language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '6'
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
  - npm run build
  - npm run deploy
branches:
  except:
    - /^v\d+\.\d+\.\d+$/